name: dragginator
description: Dragginator

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.10+10

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4

  # Securley store data in a keystore
  flutter_secure_storage: ^5.0.2

  # Shared prefs
  shared_preferences: ^2.0.9

  # Flare for animations
  flare_flutter: ^3.0.0-nullsafety.1

  asn1lib: ^1.0.3 
  
  # Websockets
  web_socket_channel: ^2.1.0

  # Platform-specific build info
  package_info_plus: ^1.3.0

  # Device-specific info
  device_info_plus: ^3.1.1

  # JSON Serialization
  json_annotation: ^4.0.0

  # Localization
  intl: ^0.17.0

  # BigDecimal alternative
  decimal: ^1.5.0

  # Logger
  logger: ^1.1.0

  webview_flutter: ^2.3.0

  bip32: ^2.0.0

  bip39: ^1.0.6
  
  # Flutter plugin for accepting incoming links - App/Deep Links (Android), Universal Links and Custom URL schemes (iOS)
  uni_links: ^0.5.1

  # SQLite
  sqflite: ^2.0.0+4

  # Android/iOS path provider
  path_provider: ^2.0.7
  
  # TouchID/FaceID
  local_auth: ^1.1.8
 
  # Eventbus
  event_taxi: ^1.0.0

  # SVG
  flutter_svg: ^0.23.0+1
  
  ffi: ^1.1.2

  flutter_launcher_icons: ^0.9.2

  # QR Codes
  qr_flutter: ^4.0.0

  # Generator
  barcode_scan2: ^4.1.4
  
  flutter_radar_chart: ^0.2.0

  flip_card: ^0.6.0

  scrolling_page_indicator:
    git: 
     url: https://github.com/redDwarf03/FlutterScrollingPageIndicator.git
     ref: master

  # HTTP client
  http: ^0.13.4

  # Easy hexadecimal encoding and decoding
  hex: ^0.2.0

  pointycastle: ^3.4.0
  
  # Vibrate
  flutter_vibrate: ^1.3.0

  # Toast
  oktoast: ^3.0.0

  # Slidable list actions
  flutter_slidable: ^0.6.0-nullsafety.0

  circular_profile_avatar: ^2.0.5

  # Lock helper
  synchronized: ^3.0.0

  # Service provider
  get_it: ^7.2.0
  
  quiver: ^3.0.1+1

  convert: ^3.0.1

  bs58check: ^1.0.2

  # Validation utilities
  validators: ^3.0.0

  # Auto resize text widget
  auto_size_text: ^3.0.0

  # Avoid keyboard from overlapping text fields
  keyboard_avoider: 
    git:
      url: https://github.com/redDwarf03/keyboard_avoider.git
      ref: master

  hash:  
    git: 
      url: https://github.com/redDwarf03/hash.git
      ref: master

  fast_base58: ^0.2.1
  
  diacritic: ^0.1.3
  
  fluttericon: ^2.0.0

  event_bus: ^2.0.0

  flutter_cube:
    git:
      url: https://github.com/redDwarf03/flutter_cube.git
      ref: master
  
  flutter_gl: ^0.0.6
  three_dart: ^0.0.1
  three_dart_jsm: ^0.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.0
  json_serializable: ^4.0.3
  # Automatically organize your dart imports
  import_sorter: ^4.6.0
  
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

flutter_icons:
  android: true
  ios: true
  image_path: "assets/dragginator_icon_bis_color.png"

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Black.ttf
        - asset: fonts/Lato-BlackItalic.ttf
        - asset: fonts/Lato-Bold.ttf
        - asset: fonts/Lato-BoldItalic.ttf
        - asset: fonts/Lato-Hairline.ttf
        - asset: fonts/Lato-HairlineItalic.ttf
        - asset: fonts/Lato-Heavy.ttf
        - asset: fonts/Lato-HeavyItalic.ttf
        - asset: fonts/Lato-Italic.ttf
        - asset: fonts/Lato-Light.ttf
        - asset: fonts/Lato-LightItalic.ttf
        - asset: fonts/Lato-Medium.ttf
        - asset: fonts/Lato-MediumItalic.ttf
        - asset: fonts/Lato-Regular.ttf
        - asset: fonts/Lato-SemiBold.ttf
        - asset: fonts/Lato-SemiBoldItalic.ttf
        - asset: fonts/Lato-Thin.ttf
        - asset: fonts/Lato-ThinItalic.ttf
    - family: AppIcons
      fonts:
        - asset: fonts/AppIcons.ttf
          weight: 500
    - family: Comfortaa
      fonts:
        - asset: fonts/Comfortaa-Bold.ttf
          weight: 700
        - asset: fonts/Comfortaa-Regular.ttf
          weight: 400
        - asset: fonts/Comfortaa-Light.ttf
          weight: 300
  assets:
    - assets/QR.svg
    - assets/icon.png
    - assets/send_animation.flr
    - assets/searchseedqr_animation_magnifyingglassonly.flr
    - assets/searchseedqr_animation_glassonly.flr
    - assets/searchseedqr_animation_qronly.flr
    - assets/searchseedmanual_animation_magnifyingglassonly.flr
    - assets/searchseedmanual_animation_glassonly.flr
    - assets/searchseedmanual_animation_seedonly.flr
    - assets/sharecard_logo.svg
    - assets/pulltosend_animation.flr
    - assets/sheethandle_animation.flr
    - assets/dragginator_background.png    
    - assets/dragginator_background_opacity70.png
    - assets/avatar_default.png
    - assets/dragginator_logo.png
    - assets/dragginator_logo_tiny.png
    - assets/dragginator_logo_start.png
    - assets/models/obj/male02/male02.obj
    - assets/textures/uv_grid_opengl.jpg
    
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  